/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainSIPFrame.java
 *
 * Created on 16/08/2010, 16:59:15
 */
package org.idde.sip.view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.beans.PropertyChangeEvent;
import javax.swing.Icon;
import javax.swing.SwingUtilities;
import org.idde.chat.controller.Properties;
import org.idde.chat.view.AbstractViewPanel;
import org.idde.sip.model.SIPManager;

/**
 *
 * @author vilson
 */
public class MainSIPFrame extends AbstractViewPanel implements WindowListener, ActionListener
{

    private String status;
    private SIPManager eventManager;

    /** Creates new form MainSIPFrame */
    public MainSIPFrame()
    {

        doWork();
        SwingUtilities.invokeLater(new Runnable()
        {
            public void run()
            {
                doWork();
            }
        });
    }

    private void doWork()
    {
        Thread thread = new Thread(new Runnable()
        {
            public void run()
            {
                eventManager = new SIPManager(MainSIPFrame.this);
            }
        });
        thread.start();

        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfURI = new javax.swing.JTextField();
        btnCall = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();

        jLabel1.setText("Nr");

        btnCall.setText("Call");
        btnCall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCallActionPerformed(evt);
            }
        });

        lblStatus.setIcon(org.idde.common.view.StatusIcons.ICON_RED);
        lblStatus.setText("not registered");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfURI, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                        .addGap(6, 6, 6)
                        .addComponent(btnCall))
                    .addComponent(lblStatus, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfURI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnCall))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblStatus))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCallActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCallActionPerformed
    {//GEN-HEADEREND:event_btnCallActionPerformed
        String URI = tfURI.getText();

        if ( ! tfURI.toString().contains("sip:") )
        {
            URI = "sip:"+URI;
        }

        if ( ! tfURI.toString().contains("@sip.vgdata.net") )
        {
            URI = URI + "@sip.vgdata.net";
        }

        eventManager.callClicked(URI);
    }//GEN-LAST:event_btnCallActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCall;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTextField tfURI;
    // End of variables declaration//GEN-END:variables

    @Override
    public void modelPropertyChange(PropertyChangeEvent evt)
    {
        // User has disconnected
        if (evt.getPropertyName().equals(Properties.AUTHENTICATED.toString()))
        {
            if (! (Boolean) evt.getNewValue())
            {
                // code here
            }
        }
    }

    public void windowOpened(WindowEvent e)
    {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void windowClosing(WindowEvent e)
    {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void windowClosed(WindowEvent e)
    {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void windowIconified(WindowEvent e)
    {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void windowDeiconified(WindowEvent e)
    {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void windowActivated(WindowEvent e)
    {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void windowDeactivated(WindowEvent e)
    {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void actionPerformed(ActionEvent e)
    {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void setLabelText(String string)
    {
        this.lblStatus.setText(string);
    }

    public void setLabelIcon(Icon icon)
    {
        this.lblStatus.setIcon(icon);
    }

    public void setStatus(String status)
    {
        this.status = status;
    }

    public String getStatus()
    {
        return status;
    }
}
